[package]
name = "Voxel-Test-1"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
vec_mem_heap = "0.*"
serde = "1.0"
serde_json = "1.0"
derive-new = "0.7"
roots = "0.0.8"
lazy_static = "1.4.0"