[package]
name = "Voxel-Test-1"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
vec_mem_heap = "0.2"
serde = "1.0"
serde_json = "1.0"
hecs = {version = "0.10", features = ["macros"]}
derive-new = "0.7"