name: Build and Deploy to External Repo

on:
  push:
    branches:
      - main  # Trigger the build on a push to the main branch of your source repo

permissions:
  contents: write  # Allow pushing to the deployment repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2  # Checkout the source code from the main repo

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true  # Ensure Rust toolchain is set for WASM target

      - name: Build WebAssembly
        run: cargo build --release --target wasm32-unknown-unknown  # Build the WASM file

      - name: Prepare Deployment Files
        run: |
          mkdir -p ./deploy
          cp ./target/wasm32-unknown-unknown/release/my_game.wasm ./deploy/
          cp index.html ./deploy/  # Copy .wasm and index.html to deploy folder

      - name: Push to Deployment Repository
        run: |
          cd deploy
          git init  # Initialize a new git repository in the deploy folder
          git remote add origin https://github.com/Karanstr/grid_game.git  # Set the remote to your deployment repo
          git checkout -b main  # Ensure we are on the main branch
          git add .  # Add all deployment files
          git commit -m "Deploy new build"  # Commit the changes
          git push --force https://Karanstr:${{ secrets.DEPLOY_REPO_TOKEN }}@github.com/Karanstr/grid_game.git main  # Push to grid_game's main branch
