name: Build and Deploy to External Repo

on:
  push:
    branches:
      - main  # Trigger the build on a push to the main branch of your source repo

permissions:
  contents: write  # Allow pushing to the deployment repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Build WebAssembly
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Set up Git repo
        run: |

          # Create the deploy directory if it doesn't exist
          mkdir -p ./deploy

          # Clone the repository into the deploy directory
          git clone https://github.com/Karanstr/grid_game.git deploy --depth 1

      - name: Add changes
        run: |
          # Navigate back to the deployment directory
          cd deploy

          # Overwrite the existing .wasm file
          cp ../target/wasm32-unknown-unknown/release/Grid-Game.wasm ./Grid-Game.wasm

          # Overwrite the data directory
          cp -r ../data ./data

      - name: Commit and Push
        run: |

          # Configure bot
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage and commit the changes
          git commit -am "Deploy new version"

          # Push to the main branch using the deployment token
          git push https://x-access-token:${{ secrets.DEPLOY_REPO_TOKEN }}@github.com/Karanstr/grid_game.git main