name: Build and Deploy to External Repo

on:
  push:
    branches:
      - main  # Trigger the build on a push to the main branch of your source repo

permissions:
  contents: write  # Allow pushing to the deployment repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Build WebAssembly
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Prepare Deployment Directory
        run: |
          mkdir -p ./deploy

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to grid_game main branch
        run: |
          # Clone the repository
          git clone https://github.com/Karanstr/grid_game.git deploy --depth 1

          # Navigate to the deploy directory
          cd deploy

          # Overwrite the existing .wasm file
          cp ../target/wasm32-unknown-unknown/release/Grid-Game.wasm ./Grid-Game.wasm

          # Stage and commit the changes
          git add .
          git commit -m "Deploy new version"

          # Push to the main branch using the deployment token
          git push https://x-access-token:${{ secrets.DEPLOY_REPO_TOKEN }}@github.com/Karanstr/grid_game.git main